

try {
    throwSomething()
} catch(err) {
    console.log(err)
}


function throwSomething(){
    throw "too big"
}
